"""empty message

Revision ID: 69d0d1053b20
Revises: eb8a5758b651
Create Date: 2019-11-18 12:19:14.377260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69d0d1053b20'
down_revision = 'eb8a5758b651'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('category_id', sa.Integer(), nullable=True))
    op.drop_constraint('questions_category_fkey', 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'categories', ['category_id'], ['id'])
    op.drop_column('questions', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('category', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key('questions_category_fkey', 'questions', 'categories', ['category'], ['id'])
    op.drop_column('questions', 'category_id')
    # ### end Alembic commands ###
