"""empty message

Revision ID: eb8a5758b651
Revises: 3d275532534c
Create Date: 2019-11-18 12:11:11.854280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb8a5758b651'
down_revision = '3d275532534c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'category',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'questions', 'categories', ['category'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.alter_column('questions', 'category',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
