"""empty message

Revision ID: fc533b9553be
Revises: 190466b56864
Create Date: 2019-11-19 15:53:30.637104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc533b9553be'
down_revision = '190466b56864'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('questions', 'answer',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('questions', 'difficulty',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('questions', 'question',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'question',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('questions', 'difficulty',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('questions', 'answer',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('categories', 'type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
